# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rtc.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 651, 491))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphViewSrc1 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphViewSrc1.setObjectName("graphViewSrc1")
        self.gridLayout.addWidget(self.graphViewSrc1, 0, 0, 1, 1)
        self.graphViewSrc4 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphViewSrc4.setObjectName("graphViewSrc4")
        self.gridLayout.addWidget(self.graphViewSrc4, 3, 1, 1, 1)
        self.graphViewSrc2 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphViewSrc2.setObjectName("graphViewSrc2")
        self.gridLayout.addWidget(self.graphViewSrc2, 0, 1, 1, 1)
        self.graphViewSrc3 = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphViewSrc3.setObjectName("graphViewSrc3")
        self.gridLayout.addWidget(self.graphViewSrc3, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboSrc2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboSrc2.setObjectName("comboSrc2")
        self.horizontalLayout_2.addWidget(self.comboSrc2)
        self.btnSrc2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSrc2.setObjectName("btnSrc2")
        self.horizontalLayout_2.addWidget(self.btnSrc2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboSrc1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboSrc1.setObjectName("comboSrc1")
        self.horizontalLayout.addWidget(self.comboSrc1)
        self.btnSrc1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSrc1.setObjectName("btnSrc1")
        self.horizontalLayout.addWidget(self.btnSrc1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboSrc3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboSrc3.setObjectName("comboSrc3")
        self.horizontalLayout_3.addWidget(self.comboSrc3)
        self.btnSrc3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSrc3.setObjectName("btnSrc3")
        self.horizontalLayout_3.addWidget(self.btnSrc3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboSrc4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboSrc4.setObjectName("comboSrc4")
        self.horizontalLayout_4.addWidget(self.comboSrc4)
        self.btnSrc4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSrc4.setObjectName("btnSrc4")
        self.horizontalLayout_4.addWidget(self.btnSrc4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(670, 10, 181, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.comboQuality = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboQuality.setObjectName("comboQuality")
        self.verticalLayout_3.addWidget(self.comboQuality)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.searchBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout_3.addWidget(self.searchBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.startBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout_3.addWidget(self.startBtn)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSrc2.setText(_translate("MainWindow", "Añadir fuente 2"))
        self.btnSrc1.setText(_translate("MainWindow", "Añadir fuente 1"))
        self.btnSrc3.setText(_translate("MainWindow", "Añadir fuente 3"))
        self.btnSrc4.setText(_translate("MainWindow", "Añadir fuente extra"))
        self.label_5.setText(_translate("MainWindow", "Calidad de grabación"))
        self.label.setText(_translate("MainWindow", "Código fuente"))
        self.searchBtn.setText(_translate("MainWindow", "Buscar"))
        self.checkBox_2.setText(_translate("MainWindow", "Código"))
        self.checkBox.setText(_translate("MainWindow", "Cámaras"))
        self.startBtn.setText(_translate("MainWindow", "Iniciar"))
        self.label_2.setText(_translate("MainWindow", "Progreso"))

